### ISSUE TITLE
github actions workflows get `SIGQUIT` (halt, failing, without GUI logs)

### ISSUE THREAD

**Issue by meowsbits** [meowsbits/core-geth#17]
My workflow runs doing VM benchmarks keep getting `QUIT`ed.

- https://github.com/meowsbits/core-geth/runs/2082622175?check_suite_focus=true
- https://pipelines.actions.githubusercontent.com/VtHrHoM4FB0KQY07S1wf6NqgybNtSHHCMXVKvrbsqBiUKuOp2M/_apis/pipelines/1/runs/122/signedlogcontent/3?urlExpires=2021-03-11T11%3A59%3A20.2224842Z&urlSigningMethod=HMACV1&urlSignature=ImqEDBw52tI8OyfHIVDtoGNw4PzIm7J7gJyiHgyqtqo%3D
```
2021-03-11T02:17:09.3908387Z BenchmarkVM/vmBitwiseLogicOperation/slt4.json-2                         	    5719	    220783 ns/op	        90.69 mgas/s	  137276 B/op	    1203 allocs/op
2021-03-11T02:17:09.4484217Z BenchmarkVM/vmBitwiseLogicOperation/xor0.json
2021-03-11T02:17:11.3951391Z BenchmarkVM/vmBitwiseLogicOperation/xor0.json-2                         	    5143	    206958 ns/op	        24.21 mgas/s	  136385 B/op	    1200 allocs/op
2021-03-11T02:17:11.3956578Z BenchmarkVM/vmBitwiseLogicOperation/xor1.json
2021-03-11T02:17:12.9015870Z BenchmarkVM/vmBitwiseLogicOperation/xor1.json-2                         	    6116	    217538 ns/op	        91.99 mgas/s	  137264 B/op	    1203 allocs/op
2021-03-11T02:17:12.9020977Z BenchmarkVM/vmBitwiseLogicOperation/xor2.json
2021-03-11T02:17:13.9997509Z BenchmarkVM/vmBitwiseLogicOperation/xor2.json-2                         	    5998	    204590 ns/op	        97.80 mgas/s	  137257 B/op	    1203 allocs/op
2021-03-11T02:17:13.9998877Z BenchmarkVM/vmBitwiseLogicOperation/xor3.json
2021-03-11T02:17:15.2961032Z BenchmarkVM/vmBitwiseLogicOperation/xor3.json-2                         	    6019	    211199 ns/op	        94.75 mgas/s	  137398 B/op	    1203 allocs/op
2021-03-11T02:17:15.2971321Z BenchmarkVM/vmBitwiseLogicOperation/xor4.json
2021-03-11T02:17:16.7141880Z BenchmarkVM/vmBitwiseLogicOperation/xor4.json-2                         	    6308	    221212 ns/op	        90.46 mgas/s	  137396 B/op	    1203 allocs/op
2021-03-11T02:17:16.7151732Z BenchmarkVM/vmBitwiseLogicOperation/xor5.json
2021-03-11T02:17:18.1994011Z BenchmarkVM/vmBitwiseLogicOperation/xor5.json-2                         	    5563	    235177 ns/op	        85.08 mgas/s	  137399 B/op	    1203 allocs/op
2021-03-11T02:17:18.2005539Z BenchmarkVM/vmBlockInfoTest/coinbase.json
2021-03-11T03:13:04.2938111Z SIGQUIT: quit
2021-03-11T03:13:05.6066186Z PC=0x476401 m=0 sigcode=0
2021-03-11T03:13:20.6598310Z 
2021-03-11T03:13:22.2044898Z goroutine 0 [idle]:
2021-03-11T03:13:24.6174552Z runtime.futex(0xe338d0, 0x80, 0x0, 0x0, 0x7ffc00000000, 0x7ffcbb9c8982, 0xe33780, 0x7ffcbb917808, 0x7ffcbb917818, 0x40f1bf, ...)
2021-03-11T03:13:26.5515555Z 	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/sys_linux_amd64.s:579 +0x21
2021-03-11T03:13:28.3631646Z runtime.futexsleep(0xe338d0, 0x0, 0xffffffffffffffff)
2021-03-11T03:13:31.8659589Z 	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/os_linux.go:44 +0x46
2021-03-11T03:13:35.0214680Z runtime.notesleep(0xe338d0)
2021-03-11T03:13:35.0216491Z 	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/lock_futex.go:159 +0x9f
2021-03-11T03:13:35.0217182Z runtime.mPark()
2021-03-11T03:13:35.0217878Z 	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:1340 +0x39
2021-03-11T03:13:35.0218525Z runtime.stopm()
2021-03-11T03:13:35.0219196Z 	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:2257 +0x92
2021-03-11T03:13:35.0219948Z runtime.findrunnable(0xc000038000, 0x0)
2021-03-11T03:13:35.0220733Z 	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:2916 +0x72e
2021-03-11T03:13:35.0221383Z runtime.schedule()
2021-03-11T03:13:35.0222114Z 	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:3125 +0x2d7
2021-03-11T03:13:35.0222760Z runtime.park_m(0xc000000f00)
2021-03-11T03:13:35.0223487Z 	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:3274 +0x9d
2021-03-11T03:13:35.0224151Z runtime.mcall(0x84c240)
2021-03-11T03:13:35.0224847Z 	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/asm_amd64.s:327 +0x5b
2021-03-11T03:13:35.0225307Z 
2021-03-11T03:13:35.0225792Z goroutine 1 [chan receive, 61 minutes]:
2021-03-11T03:13:35.0226373Z testing.(*B).run1(0xc000100000, 0xc0000a4008)
2021-03-11T03:13:35.0227187Z 	/opt/hostedtoolcache/go/1.16.0/x64/src/testing/benchmark.go:234 +0xa5
2021-03-11T03:13:35.5233213Z testing.(*B).Run(0xc000101680*** Test killed: ran too long (1h1m0s).
2021-03-11T03:13:35.5614229Z signal: killed
2021-03-11T03:13:36.1206043Z FAIL	github.com/ethereum/go-ethereum/tests	3713.216s
2021-03-11T03:13:36.7118655Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2021-03-11T03:13:36.7118889Z ##[error]Process completed with exit code 143.
2021-03-11T03:13:37.5116674Z Cleaning up orphan processes
```

**Comment by meowsbits** [comment]
Thanks to @ziogaschr, it's apparent that the test above ran too long (1h 1m) and was killed by Go for exceeding the test timeout (60m).

BUT, the next Action run shows a similar problem, which is quitted under more mysterious circumstances.
- https://github.com/meowsbits/core-geth/runs/2086042534?check_suite_focus=true
- https://pipelines.actions.githubusercontent.com/VtHrHoM4FB0KQY07S1wf6NqgybNtSHHCMXVKvrbsqBiUKuOp2M/_apis/pipelines/1/runs/123/signedlogcontent/3?urlExpires=2021-03-11T13%3A16%3A38.6603085Z&urlSigningMethod=HMACV1&urlSignature=hDe1GRJZMvOPXrUZQ9G%2BYOB8wal%2Bj71yC1KQ5wVHNiQ%3D

```
2021-03-11T12:38:56.9200998Z BenchmarkVM/vmArithmeticTest/divBoostBug.json
2021-03-11T12:39:10.4585085Z BenchmarkVM/vmArithmeticTest/divBoostBug.json-2               	   38619	     35734 ns/op	        70.40 mgas/s	   11459 B/op	      55 allocs/op
2021-03-11T12:39:10.4590785Z BenchmarkVM/vmArithmeticTest/divByNonZero0.json
2021-03-11T12:39:23.8122543Z BenchmarkVM/vmArithmeticTest/divByNonZero0.json-2             	   40736	     30336 ns/op	        75.90 mgas/s	   11395 B/op	      55 allocs/op
2021-03-11T12:39:23.8129202Z BenchmarkVM/vmArithmeticTest/divByNonZero1.json
2021-03-11T12:39:37.7056864Z BenchmarkVM/vmArithmeticTest/divByNonZero1.json-2             	   43532	     28235 ns/op	        19.32 mgas/s	   10484 B/op	      51 allocs/op
2021-03-11T12:39:37.7069884Z BenchmarkVM/vmArithmeticTest/divByNonZero2.json
2021-03-11T12:39:53.4483638Z BenchmarkVM/vmArithmeticTest/divByNonZero2.json-2             	   42764	     28171 ns/op	        19.09 mgas/s	   10484 B/op	      51 allocs/op
2021-03-11T12:39:53.4489440Z BenchmarkVM/vmArithmeticTest/divByNonZero3.json
2021-03-11T12:40:04.3453668Z BenchmarkVM/vmArithmeticTest/divByNonZero3.json-2             	   38727	     31370 ns/op	        76.54 mgas/s	   11395 B/op	      55 allocs/op
2021-03-11T12:40:04.3460527Z BenchmarkVM/vmArithmeticTest/divByZero.json
2021-03-11T12:40:17.8531552Z BenchmarkVM/vmArithmeticTest/divByZero.json-2                 	   41278	     28092 ns/op	        19.22 mgas/s	   10484 B/op	      51 allocs/op
2021-03-11T12:40:17.8537621Z BenchmarkVM/vmArithmeticTest/divByZero_2.json
2021-03-11T13:00:07.7732979Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2021-03-11T13:00:07.8153453Z ##[error]Process completed with exit code 143.
2021-03-11T13:00:09.5185041Z Cleaning up orphan processes
```

**Comment by ziogaschr** [comment]
Can you please try re-run it and see if this error persists? Might be some random/rear issue with their infrastructure, as it has received a shutdown signal and timeout wise it had more minutes to use.

**Comment by meowsbits** [comment]
Here it is again

- https://github.com/meowsbits/core-geth/runs/2086641037?check_suite_focus=true
```
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_3.json
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_3.json-2      	   14743	     82049 ns/op	       386.4 mgas/s	   25645 B/op	     388 allocs/op
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_30.json
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_30.json-2     	   10000	    109700 ns/op	       357.5 mgas/s	   25639 B/op	     388 allocs/op
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_31.json
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_31.json-2     	   10000	    109605 ns/op	       356.9 mgas/s	   25642 B/op	     388 allocs/op
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_32.json
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_32.json-2     	   10000	    105118 ns/op	       393.1 mgas/s	   25724 B/op	     389 allocs/op
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_33.json
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_33.json-2     	   10000	    107343 ns/op	       378.3 mgas/s	   25724 B/op	     389 allocs/op
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_4.json
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_4.json-2      	   14148	     90012 ns/op	       340.8 mgas/s	   25641 B/op	     388 allocs/op
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_5.json
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_5.json-2      	   14248	     88133 ns/op	       355.2 mgas/s	   25642 B/op	     388 allocs/op
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_6.json
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_6.json-2      	   10000	    156013 ns/op	       309.2 mgas/s	   25656 B/op	     388 allocs/op
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_7.json
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_7.json-2      	   14254	     91825 ns/op	       357.4 mgas/s	   25639 B/op	     388 allocs/op
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_8.json
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_8.json-2      	    1200	  42475250 ns/op	         2.250 mgas/s	   25646 B/op	     388 allocs/op
BenchmarkVM/vmArithmeticTest/expPowerOf256Of256_9.json
signal: killed
FAIL	github.com/ethereum/go-ethereum/tests	1244.661s
FAIL
```

- https://pipelines.actions.githubusercontent.com/VtHrHoM4FB0KQY07S1wf6NqgybNtSHHCMXVKvrbsqBiUKuOp2M/_apis/pipelines/1/runs/126/signedlogcontent/3?urlExpires=2021-03-11T19%3A28%3A52.3303820Z&urlSigningMethod=HMACV1&urlSignature=iVR2qWr%2Bf4dtyfpLiuKCDZ9uYdEF591NdLmka49hLPM%3D
```
2021-03-11T13:44:37.2765343Z ##[section]Starting: Request a runner to run this job
2021-03-11T13:44:37.9692434Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'ubuntu-latest'
2021-03-11T13:44:37.9692532Z Can't find any online and idle self-hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2021-03-11T13:44:37.9693078Z Found online and idle hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2021-03-11T13:44:38.1513688Z ##[section]Finishing: Request a runner to run this job
```
